[tool.poetry]
name = "fastapi-sqlalchemy"
version = "0.1.0"
description = ""
authors = ["uuip <uuip@users.noreply.github.com>"]
readme = "README.md"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
priority = "default"

[tool.poetry.dependencies]
python = "^3.11"
wheel = ">=0.40.0"
setuptools = ">=67.7.2"

sqlalchemy = "^2.0.19"
uvloop = { version = "^0.17.0", markers = "platform_system != 'Windows'" }
fastapi = "^0.100.0"
uvicorn = "^0.23.1"
psycopg2 = "^2.9.6"
asyncpg = "^0.28.0"
pydantic = "^2.0.3"
pydantic-settings = "^2.0.2"
tzdata = { version = "^2023.3", markers = "platform_system == 'Windows'" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
