[tool.poetry]
name = "fastapi-sqlalchemy"
version = "0.1.0"
description = ""
authors = ["uuip <uuip@users.noreply.github.com>"]
readme = "README.md"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
priority = "default"

[tool.poetry.dependencies]
python = "^3.11"
wheel = ">=0.42.0"
setuptools = ">=69.0.3"

sqlalchemy = { extras = ["asyncio"], version = "^2.0.25" }
fastapi = "^0.109.2"
uvicorn = "^0.27.0"
asyncpg = "^0.29.0"
pydantic = "^2.6.0"
pydantic-settings = "^2.1.0"
tzdata = { version = "^2023.4", markers = "platform_system == 'Windows'" }
uvloop = { version = "^0.19.0", markers = "platform_system != 'Windows'" }
psycopg = {extras = ["binary", "pool"], version = "^3.1.18"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
