[tool.poetry]
name = "fastapi-sqlalchemy"
version = "0.1.0"
description = ""
authors = ["uuip <uuip@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
priority = "primary"

[tool.poetry.dependencies]
python = "^3.12"
wheel = ">=0.43.0"
setuptools = ">=71.1.0"

sqlalchemy = { extras = ["asyncio"], version = "^2.0.31" }
fastapi = "^0.111.1"
uvicorn = "^0.30.3"
asyncpg = "^0.29.0"
pydantic = "^2.8.2"
pydantic-settings = "^2.3.4"
tzdata = { version = "^2024.1", markers = "platform_system == 'Windows'" }
uvloop = { version = "^0.19.0", markers = "platform_system != 'Windows'" }
psycopg = {extras = ["binary"], version = "^3.2.1"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = "^1.7.4"
alembic = "^1.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
