[tool.poetry]
name = "fastapidemo"
version = "0.1.0"
description = ""
authors = ["uuip <uuip@users.noreply.github.com>"]
readme = "README.md"

[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "default"

[tool.poetry.dependencies]
python = "^3.10"
wheel = ">=0.40.0"
setuptools = ">=67.7.2"

sqlalchemy = { version = ">=2.0.12", allow-prereleases = true }
greenlet = ">=2.0.2"
uvloop = "^0.17.0"
fastapi = ">=0.95.1"
uvicorn = ">=0.22.0"
psycopg2 = "^2.9.6"
asyncpg = ">=0.27.0"
pydantic = { extras = ["dotenv"], version = ">=1.10.7" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
